import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en": {},
        "ar": {
          "chapters": "الفصول",
          "Recently Added": "اضيفت مؤخرا",
          "Library": "المكتبة",
          "Settings": "الاعدادات",
          "Discover": "اكتشف",
          "search": "بحث",
          "Stories": "القصص",
          "genres": "الاقسام",
          "about": "عن التطبيق",
          "contact us": "تواصل معنا",
          "share": "شارك",
          "rate": "قيم",
          "language": "اللغة",
          "dark mode": "الوضع الليلي",
          "light mode": "الوضع النهاري",
          "purple mode": "الوضع البنفسجي",
          "Overview": "نبذة ",
          "read": "اقرأ",
          "read more": "اقرأ المزيد",
          "read less": "اقرأ اقل",
          "no internet": "لا يوجد اتصال بالانترنت",
          "Oops! couldn't find any chapters":"عفوا! لم يتم العثور على اي فصول",
          "Hikayat": "حكايات",
          "Theme": "الوضع",
          "Font Size": "حجم الخط",
          "Font family": "نوع الخط",
          "Amiri": "عميري",
          "Cairo": "كايرو",
          "Changa": "تشانجا",
          "ElMessiri": "المسيري",
          "Harmattan": "هرماتان",
          "Kufi": "كوفي",
          "Lateef": "لاتيف",
          "MarkaziText": "مركزي",
          "ReemKufi": "ريم كوفي",
          "Tajawal": "تاجوال",
          "Mada": "مادا",
          "Marhey": "مرهي",
          "SansArabic": "سانس عربي",
          "Lalezar": "لاليزار",
          "Add Background Image": "اضف صورة خلفية",
          "Writer": "الكاتب",
          
        },
      };
}
