// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJD5MJewwk8oRoRjwK88_ybz_IuHLhgs',
    appId: '1:192158253933:android:9dd9652e26359b86749064',
    messagingSenderId: '192158253933',
    projectId: 'hikayat-969a7',
    storageBucket: 'hikayat-969a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwgvJ9DiOjfN-8hTOkJb2N6hoKOAv8Fek',
    appId: '1:192158253933:ios:32deffcac7c4ce2b749064',
    messagingSenderId: '192158253933',
    projectId: 'hikayat-969a7',
    storageBucket: 'hikayat-969a7.appspot.com',
    androidClientId: '192158253933-5qej5tnvl3b0it65aqd28nfptneajthu.apps.googleusercontent.com',
    iosClientId: '192158253933-qgtc0k5rret2ukl8jqbq4bgu2b0qlehh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hikayat',
  );
}
